### ISSUE TITLE
Failure scanning negative floating-point decimals

### ISSUE THREAD

**Issue by petrmanek** [eliaskosunen/scnlib#106]
Hi, I discovered a potentially serious bug in v1.1. The following code does not correctly scan a negative decimal value:

```cpp
double scanned;
scn::scan("-1.5036", "{}", scanned);
std::printf("%f\n", scanned);
// prints 1.5036 (without minus sign)
```

The same goes for:

```cpp
auto scanned = scn::scan_value<double>("-1.5036");
std::printf("%f\n", scanned.value());
// prints 1.5036 (without minus sign)
```

I tried using the `{:f}` format string without improvement. Am I doing something wrong? My current hypothesis is that the minus sign is discarded because it is considered not to be a part of the scanned value. I would appreciate a second opinion.

**Comment by petrmanek** [comment]
One addendum: I have just tried reproducing this the latest v1 branch and found that this bug is present only with `SCN_DISABLE_LOCALE=ON`

**Comment by petrmanek** [comment]
One more addendum: v2 (the latest master) appears _not_ to produce this bug.

**Comment by eliaskosunen** [comment]
If the issue is really only present in v1 with `SCN_DISABLE_LOCALE` on, I don't think I'll do anything about it myself: I don't really intend to touch v1 anymore. Your hypothesis is likely correct, as `SCN_DISABLE_LOCALE` isn't and wasn't really tested properly in v1.

Thanks for the report, anyway!
