### ISSUE TITLE
Prompt<char> does not flush/discard rest of the buffer from stdin

### ISSUE THREAD

**Issue by RazielXYZ** [eliaskosunen/scnlib#123]
Windows, scnlib 3.0.1, msvc latest.
Repeated calls to prompt seem to return/start with the whitespace from the previous call.
For example:

```c++
#include <scn/scan.h>
#include <print>

int main(int argc, char* argv[])
{
    if (auto result = scn::prompt<char>("Do you want to do a thing? Say Y!\n", "{}")) {
        if (auto [c] = result->values(); c == 'Y') {
            std::print("You said {}! Did a thing!", c);
        } else {
            std::print("You said {}! Did not do the thing!", c);
        }
    }
    if (auto result = scn::prompt<char>("Do you want to do another thing? Say Y!\n", "{}")) {
        if (auto [c] = result->values(); c == 'Y') {  
            std::print("You said {}! Did another thing!", c);
        } else {
            std::print("You said {}! Did not do the other thing!", c);
        }
    }
    return 0;
}
```
If we input 'Y' to the first prompt, the first will read 'Y', and the second will read '\n' regardless of user input.
If we input "Yes" to the first prompt, the first will read 'Y', and the second will read 'e' immediately without prompting for input.
Adding a fflush on stdin in between the prompts does not seem to change anything, and `scn::scan<scn::discard<char>>(stdin, "{}")` waits for input making it unsuitable for just clearing it. Changing the format string to {}\n or {}\r\n does not appear to work correctly either.

On a semi-unrelated note, prompting for a std::string (in general, regardless of repeated prompts) does not return after one line of input, and crashes after the second line of input.

I'm not sure if these behaviors are intended, but the examples suggest that they are not.

**Comment by eliaskosunen** [comment]
The issue here is twofold:

First, `scn::scan<char>` (and consequently, `scn::input` and `scn::prompt`) read a single `char` from their source, and nothing else. This means that `scn::input<char>("{}")` will leave (a possible) `\n` in `stdin`, as it's just another character, after all. Indeed, if `stdin` only contained a `\n`, `scn::input<char>("{}")` would read and return that.

This is the same behavior that would be achieved with `scanf`:

```cpp
char a, b;
scanf("%c", &a);
scanf("%c", &b);
// If stdin contains "a\nb\b",
// a == 'a', and b == '\n'
```

The remedy here is the same as with `scanf`: use the format string to skip unwanted whitespace. As with `scanf`, a character of whitespace in the format string instructs to skip all whitespace in the input. Therefore, the following will work:

```cpp
// " {}":
// skip whitespace found in the input, and read a single `char`
auto res1 = scn::input<char>(" {}");
auto res2 = scn::input<char>(" {}");
```

The key insight is to use the space _before_ the `{}`. If is after the `{}`, `scn::input` will read `stdin` until it finds a non-whitespace character (or EOF), which is probably not what you want.

Another approach would be to read `stdin` yourself (maybe with `getline`), in a line-oriented fashion, and then use `scn::scan` to parse the input. This is, again, the same thing you'd do with `scanf`.

The other issue was that sometimes the library was too eager to read new input from `stdin`, when that wasn't really necessary, which would cause unnecessary blocking due to waiting on `stdin`. This has now been fixed in 82a99201f2bc658f3e333b6e45a8e13efb371816. This will also make the `scn::discard` trick you mentioned work properly.

As for the issue regarding `std::string`, I'm not able to replicate that.
