### ISSUE TITLE
How to scan string of a fixed length

### ISSUE THREAD

**Issue by evskola** [eliaskosunen/scnlib#131]
Hi,

When implementing a custom scanner I want to read a fixed length strings from the input.
I tryed to follow an example from here https://github.com/eliaskosunen/scnlib/issues/19 but it looks the API changed a lot since then.

Could you please provide an example how I can read a series of fixed length strings?

Some more context: I want to read a thing of the following format `"{}_{}_{}"` (first must be of length 10, second must be 20 and thirdmust be 4).

**Comment by eliaskosunen** [comment]
The API has indeed changed quite substantially since then.

The number of characters is controlled by the width and precision specifiers in the format string: https://www.scnlib.dev/group__format-string.html#width. The "width" controls the minimum number of characters to read, and the "precision" the maximum, respectively. To force a fixed length, you can use both. When reading strings, combine this with the `c` format specifier to read characters until the field precision is reached, and not just until whitespace (which is the default behavior for strings): https://www.scnlib.dev/group__format-string.html#type-string

For example:
```cpp
struct mytype {
    std::string a, b, c;
};

template <>
struct scn::scanner<mytype> {
    template <typename ParseContext>
    constexpr auto parse(ParseContext& pctx)
        -> scn::scan_expected<typename ParseContext::iterator>
    {
        return pctx.begin();
    }

    template <typename Context>
    auto scan(mytype& val, Context& ctx)
        -> scn::scan_expected<typename Context::iterator>
    {
        // {:10.10c}
        // `10` -> "width" is 10 == minimum no. of characters is 10
        // `.10` -> "precision" is 10 == maximum no. of characters is 10
        // `c` -> read until "precision" characters have been read
        return scn::scan<std::string, std::string, std::string>(ctx.range(), "{:10.10c}_{:20.20c}_{:4.4c}")
            .transform([&](auto res) {
                std::tie(val.a, val.b, val.c) = std::move(res.values());
                return res.begin();
            });
    }
};

int main() {
    auto res = scn::scan<mytype>("0123456789_aabbccddeeffgghhiijj_1234", "{}");
    if (res) {
        std::println("{}_{}_{}", res->value().a, res->value().b, res->value().c);
        // Prints "0123456789_aabbccddeeffgghhiijj_1234"
    }
}
```

Two additional points to note:
 * The "width" and "precision" fields don't strictly specify the number of _characters_ to read (for whatever that even means in a Unicode world), but the number of _field width units_ to read. This is the same thing that's used in {fmt} and `std::format`: https://www.scnlib.dev/group__format-string.html#width
 * The return value of `ctx.range()` inside `scn::scanner::scan` is just a range. You can pass it to `scn::scan`, like we do above, or you could just `std::ranges::copy_n` from it, if you wish.
